=== mikekeehnen/ChuckChuckle/apps/mesh/src/schemas/chuck-joke.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "categories": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "created_at": {
      "type": "string"
    },
    "icon_url": {
      "type": "string",
      "format": "uri"
    },
    "id": {
      "type": "string"
    },
    "updated_at": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "format": "uri"
    },
    "value": {
      "type": "string"
    }
  },
  "required": ["categories", "created_at", "icon_url", "id", "updated_at", "url", "value"],
  "additionalProperties": true
}

=== mikekeehnen/ChuckChuckle/apps/mesh/src/samples/random-joke.response.json
{
  "categories": ["dev"],
  "created_at": "2020-01-05 13:42:19.576875",
  "icon_url": "https://api.chucknorris.io/img/avatar/chuck-norris.png",
  "id": "RANDOM_ID",
  "updated_at": "2020-01-05 13:42:19.576875",
  "url": "https://api.chucknorris.io/jokes/RANDOM_ID",
  "value": "Chuck Norris can divide by zero."
}
